build c mod

diff --git a/merge b/merge
--- a/merge
+++ b/merge
@@ -22,3 +22,7 @@ if [ ".$1" = ".rc" ]; then
     cd ./lib && rm test_*.lua
     )
 fi
+
+for modname in $(ls dep-build); do
+    sh dep-build/$modname || { echo "Error build $modname"; exit 1; }
+done
